# Project information
site_name: Local Payment Solution
site_description: 'An example MkDocs project using the Material theme'
site_url: 'https://adorsys-gis.github.io/iwym-backend'

# Theme settings
theme:
  name: material
  palette:
    scheme: slate
    primary: teal

# Navbar settings (site structure)
nav:
  - Home: README.md
  - Docs:
    - ARC42: ARC42.md
    - Docs: tech.md

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Repository configuration (for the edit link on pages)
repo_name: ADORSYS-GIS/iwym-backend
repo_url: https://github.com/ADORSYS-GIS/iwym-backend
edit_uri: edit/main/docs/